### ISSUE TITLE
Installer Not Working?

### ISSUE THREAD

**Issue by mattlbailey** [DHTMLGoodies/dhtmlchess#3]
After uploading to my web server, and hitting the installer, I only get a page that says DHTMLchess 3.0 at the top.  Where is the installer, and how is it supposed to work?
![screen shot 2014-11-27 at 9 04 00 am](https://cloud.githubusercontent.com/assets/8498395/5218638/949c87d6-7614-11e4-8bae-c2880c083428.png)

I even created a new database, renamed the connection.template.php to connection.php and updated the connection details.  I also have PHP 5.5 and the required extensions.

**Comment by DHTMLGoodies** [comment]
A lot of work has been done on DTHML Chess during the last months. The installer has now been removed and the standard version is file based(i.e. no installation required). In most cases, it should work out of the box

There is also a WordPress version which is in public beta testing  phase(www.dhtmlchess.com/wordpress.php). A free commercial license is granted to everyone participating in the beta testing.
