### ISSUE TITLE
Installer doesn't work

### ISSUE THREAD

**Issue by crapomat** [DHTMLGoodies/dhtmlchess#4]
Hi, 
i uploaded your project to my domain, but when I try to run installer, it says "Syntax Error: Unexpected token <". 
I made screenshot here: http://clinde.de/dump/dhtml-installer.png (pw is deleted for screenshot)

When i press Test Connection and when i press Finish it says it. So Installer doesn't run, What did i wrong? Is this only my installation or anyone else has this issue? Any help or hints?

It gives that error message for any combination of name/pass etc.

**Comment by cemslord** [comment]
use chessboardjs its responve and chess.js  all together you find in github.
developer  still not response in long time...

**Comment by crapomat** [comment]
Thank you for that hints. I tried your pgnviewer, it looks promising to me. I want to make a website for a local chess club and I want to have a "upload your game" function on that page. So users can upload their games and have them listed on their page. pgnviewer seems like the right tool to display their .pgn files. I also want an "autoplay" feature, so users don't have to push a button for each move. I didn't read through all manuals, could you help me with that button?

**Comment by DHTMLGoodies** [comment]
A lot of work has been done on DTHML Chess during the last months. The installer has now been removed and the standard version is file based(i.e. no installation required). In most cases, it should work out of the box

There is also a WordPress version which is in public beta testing  phase(www.dhtmlchess.com/wordpress.php). A free commercial license is granted to everyone participating in the beta testing.
