### ISSUE TITLE
LudoDB

### ISSUE THREAD

**Issue by Evgenii89** [DHTMLGoodies/dhtmlchess#5]
I have installed dthml-chess on my server, but when I run www.myserver.connection.php I see "Fatal error: Class 'LudoDB' not found in". What I should to do?

**Comment by DHTMLGoodies** [comment]
The Installer has been removed from DHTML Chess. DHTML Chess should now work out of the box without any installation. There is also a WordPress version which is in public beta testing phase(www.dhtmlchess.com/wordpress.php).
