### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by Maeggi** [DHTMLGoodies/dhtmlchess#6]
Hi,
the installation instructions is old?. Some folders do not exist!
i have download and upload manually. 
But i have a white site: http://your-server-url/installer/index.php
1. Open router.php in an editor and configure a database connection. ???
//You mean "connection.template.php" and rename to "connection.php"?!
2. Open the following url in your browser
http://your-server-url/ChessDBInstaller/install
//I have no folders with these names!
//You mean http://your-server-url/installer/index.php

And LudoDB is not include?

I need a correct installation guide, with install LudoDB manuelly.

Best
Marco

**Comment by DHTMLGoodies** [comment]
The installer has been removed from DHTML Chess. There is one version which is file based. That one should work out of the box without any installation.

There is also a version for Wordpress which uses MySQL to save games. That version is in public betatesting(www.dhtml-chess.com/wordpress.php) and will be released soon.
