### ISSUE TITLE
This should not be called "winning chess sacrifices and combinations."

### ISSUE THREAD

**Issue by ariamcmann** [DHTMLGoodies/dhtmlchess#7]
The PGN file says on every game "1001 Winning Chess Sacrifices." But, there are only 366 games. Of the 366 games, 91 progress to a checkmate. And upon closer review of those 91, several of them are not winning. For instance, this game is said for "white to move & win" and is purported as follows:
[Event "White to move & win"]
[Site "?"]
[Date "1998.??.??"]
[Round "?"]
[White "1001 Winning Chess Sacrifices"]
[Black "and Combinations"]
[Result "1-0"]
[Annotator "Magne,Alf"]
[SetUp "1"]
[FEN "r1b2r2/5P1p/ppn3pk/2p1p1Nq/1bP1PQ2/3P4/PB4BP/1R3RK1 w - - 0 1"]
[PlyCount "19"]
[EventDate "1998.??.??"]

1.Ne6+ g5 2.Qf6+ Qg6 3.Bc1 Bd2 4.Bxd2 Bxe6 5.Bxg5+ Kh5 6.Bf3+ Bg4 7.Bxg4+ Kxg4 8.Rf4+ exf4 9.Qxf4+ Kh5 10.Qh4# 1-0

But, on move three, black could simply reply by taking white's queen:
1. Ne6+ g5 2. Qf6+ Qg6 3. Bc1 Qxf6
So, this collection should be refined and republished. And, since so many aren't mates, perhaps renamed to "chess puzzles" when sure that there are forceful continuations.

**Comment by ariamcmann** [comment]
The PGN file says on every game "1001 Winning Chess Sacrifices." But, there are only 366 games. Of the 366 games, 91 progress to a checkmate. And upon closer review of those 91, several of them are not winning. For instance, this game is said for "white to move & win" and is purported as follows:
[Event "White to move & win"]
[Site "?"]
[Date "1998.??.??"]
[Round "?"]
[White "1001 Winning Chess Sacrifices"]
[Black "and Combinations"]
[Result "1-0"]
[Annotator "Magne,Alf"]
[SetUp "1"]
[FEN "r1b2r2/5P1p/ppn3pk/2p1p1Nq/1bP1PQ2/3P4/PB4BP/1R3RK1 w - - 0 1"]
[PlyCount "19"]
[EventDate "1998.??.??"]

1.Ne6+ g5 2.Qf6+ Qg6 3.Bc1 Bd2 4.Bxd2 Bxe6 5.Bxg5+ Kh5 6.Bf3+ Bg4 7.Bxg4+ Kxg4 8.Rf4+ exf4 9.Qxf4+ Kh5 10.Qh4# 1-0

But, on move three, black could simply reply by taking white's queen:

1. Ne6+ g5 2. Qf6+ Qg6 3. Bc1 Qxf6

So, this collection should be refined and republished. And, since so many aren't mates, perhaps renamed to "chess puzzles" when sure that there are forceful continuations.

**Comment by ariamcmann** [comment]
The PGN file says on every game "1001 Winning Chess Sacrifices." But, there are only 366 games. Of the 366 games, 91 progress to a checkmate. And upon closer review of those 91, several of them are not winning. For instance, this game is said for "white to move & win" and is purported as follows:
[Event "White to move & win"]
[Site "?"]
[Date "1998.??.??"]
[Round "?"]
[White "1001 Winning Chess Sacrifices"]
[Black "and Combinations"]
[Result "1-0"]
[Annotator "Magne,Alf"]
[SetUp "1"]
[FEN "r1b2r2/5P1p/ppn3pk/2p1p1Nq/1bP1PQ2/3P4/PB4BP/1R3RK1 w - - 0 1"]
[PlyCount "19"]
[EventDate "1998.??.??"]

1.Ne6+ g5 2.Qf6+ Qg6 3.Bc1 Bd2 4.Bxd2 Bxe6 5.Bxg5+ Kh5 6.Bf3+ Bg4 7.Bxg4+ Kxg4 8.Rf4+ exf4 9.Qxf4+ Kh5 10.Qh4# 1-0

But, on move three, black could simply reply by taking white's queen:

1. Ne6+ g5 2. Qf6+ Qg6 3. Bc1 Qxf6

So, this collection should be refined and republished. And, since so many aren't mates, perhaps renamed to "chess puzzles" when sure that there are forceful continuations.

**Comment by ariamcmann** [comment]
The PGN file says on every game "1001 Winning Chess Sacrifices." But, there are only 366 games. Of the 366 games, 91 progress to a checkmate. And upon closer review of those 91, several of them are not winning. For instance, this game is said for "white to move & win" and is purported as follows:
[Event "White to move & win"]
[Site "?"]
[Date "1998.??.??"]
[Round "?"]
[White "1001 Winning Chess Sacrifices"]
[Black "and Combinations"]
[Result "1-0"]
[Annotator "Magne,Alf"]
[SetUp "1"]
[FEN "r1b2r2/5P1p/ppn3pk/2p1p1Nq/1bP1PQ2/3P4/PB4BP/1R3RK1 w - - 0 1"]
[PlyCount "19"]
[EventDate "1998.??.??"]

1.Ne6+ g5 2.Qf6+ Qg6 3.Bc1 Bd2 4.Bxd2 Bxe6 5.Bxg5+ Kh5 6.Bf3+ Bg4 7.Bxg4+ Kxg4 8.Rf4+ exf4 9.Qxf4+ Kh5 10.Qh4# 1-0

But, on move three, black could simply reply by taking white's queen:

1. Ne6+ g5 2. Qf6+ Qg6 3. Bc1 Qxf6

So, this collection should be refined and republished. And, since so many aren't mates, perhaps renamed to "chess puzzles" when sure that there are forceful continuations.

**Comment by ariamcmann** [comment]
The PGN file says on every game "1001 Winning Chess Sacrifices." But, there are only 366 games. Of the 366 games, 91 progress to a checkmate. And upon closer review of those 91, several of them are not winning. For instance, this game is said for "white to move & win" and is purported as follows:
[Event "White to move & win"]
[Site "?"]
[Date "1998.??.??"]
[Round "?"]
[White "1001 Winning Chess Sacrifices"]
[Black "and Combinations"]
[Result "1-0"]
[Annotator "Magne,Alf"]
[SetUp "1"]
[FEN "r1b2r2/5P1p/ppn3pk/2p1p1Nq/1bP1PQ2/3P4/PB4BP/1R3RK1 w - - 0 1"]
[PlyCount "19"]
[EventDate "1998.??.??"]

1.Ne6+ g5 2.Qf6+ Qg6 3.Bc1 Bd2 4.Bxd2 Bxe6 5.Bxg5+ Kh5 6.Bf3+ Bg4 7.Bxg4+ Kxg4 8.Rf4+ exf4 9.Qxf4+ Kh5 10.Qh4# 1-0

But, on move three, black could simply reply by taking white's queen:

1. Ne6+ g5 2. Qf6+ Qg6 3. Bc1 Qxf6

So, this collection should be refined and republished. And, since so many aren't mates, perhaps renamed to "chess puzzles" when sure that there are forceful continuations.

**Comment by DHTMLGoodies** [comment]
I also noticed this.

I have created an analysis tool in DHTML Chess which uses Stockfish JS to parse the games and look for forced checkmates and exclude games which doesn not contain ONE forced line to checkmate.

These new parsed puzzles has been included in the latest versions of DHTML Chess. (pgn/tactic-checkmates.pgn).
